#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yoj?serverTimezone=UTC
    username: root
    password: 123456

#开启debug模式
debug: true

#禁用缓存
spring.thymeleaf.cache: false

#Property 'configuration' and 'configLocation' can not specified with together
#开启驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
