jasypt:
  encryptor:
    password: lmz
#    algorithm: PBEWithMD5AndDES
#配置数据源
spring:
  redis:
    host: 106.54.94.80
  datasource:
    url: jdbc:mysql://localhost:3306/yoj?serverTimezone=UTC
    username: ENC({2IL6K8NI+eUHYpu8AsfB7Q==})
    password: ENC({+u6jN11/Ykzl5kHU0rg2Ew==})
    sql-script-encoding:
    cache:
      redis:
        time-to-live:
    #DDL
    #schema:
    #  - classpath:department.sql
    #DML
    #data:
    # - classpath:insert-dept.sql
    #2.0需要开启
    #initialization-mode: always


#开启debug模式
debug: true

#禁用缓存
spring.thymeleaf.cache: false

#Property 'configuration' and 'configLocation' can not specified with together
#开启驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


